name = "large-field-analyzer"
type = "javascript"
account_id = "5ad2ddf9aa06683d90aa5df60149f527"
compatibility_date = "2023-10-25"

[build]
upload_format = "service-worker"

# Production Environment
[env.production]
route = "https://your-production-domain.com/your-route*"
workers_dev = false
vars = { MONGODB_ENDPOINT = "your_mongodb_endpoint", COLLECTION_NAME = "your_collection_name", DATABASE_NAME = "your_database_name", DATA_SOURCE_NAME = "your_data_source_name", API_KEY = "your_api_key" }

# Staging Environment
[env.staging]
route = "https://your-staging-domain.com/your-route*"
workers_dev = false
vars = { MONGODB_ENDPOINT = "your_mongodb_endpoint", COLLECTION_NAME = "your_collection_name", DATABASE_NAME = "your_database_name", DATA_SOURCE_NAME = "your_data_source_name", API_KEY = "your_api_key" }

# Development Environment
[env.dev]
name = "large-field-analyzer-dev"
workers_dev = true
vars = { MONGODB_ENDPOINT = "your_mongodb_endpoint", COLLECTION_NAME = "your_collection_name", DATABASE_NAME = "your_database_name", DATA_SOURCE_NAME = "your_data_source_name", API_KEY = "your_api_key" }
