name = "large-field-analyzer"
type = "javascript"
account_id = "5ad2ddf9aa06683d90aa5df60149f527"
zone_id = "your-cloudflare-zone-id"
compatibility_date = "2023-10-25"

[build]
upload_format = "service-worker"

[env.production]
route = "example.com/your-route*"
workers_dev = false

[env.staging]
route = "staging.example.com/your-route*"
workers_dev = false

[env.dev]
name = "your-worker-name-dev"
workers_dev = true

# Add other configuration as needed
